name: arplayground
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ar_flutter_plugin: ^0.7.3
  path_provider: ^2.1.1
  flutter_archive: ^5.0.0
  model_viewer_plus: ^1.7.0
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  google_fonts: ^6.1.0
  simple_animations: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/models/Giulettina.glb
    # - assets/models/F1.3mf
    - assets/models/cyber.glb
    - assets/BB.png
    - assets/models/mercedesAMGT.glb
    - assets/models/jaguarFtype.glb
    - assets/models/arsixc.glb
    - assets/models/volvo.glb
    - assets/models/mastang.glb
    - assets/models/porshe.glb
    - assets/models/jhtype.glb
    - assets/models/ferari.glb
    - assets/models/ferrari.glb
    - assets/models/lamborgundi.glb
    - assets/models/mclaren.glb
    - assets/images/welcome.gif